language: python
python:
  - "3.6"
  - "3.7"

env:
  global:
    - INSTALL_TYPE=setup

matrix:
  include:
    - name: Test in Docker Ubuntu 20.04
      env:
        - INSTALL_TYPE=docker
      services:
        - docker
      before_install:
        - docker build --force-rm=true -t kalliope-ubuntu2004 -f docker/testing_ubuntu_20_04.dockerfile .
      script:
        - docker run -it --rm -e TRAVIS_BRANCH=${TRAVIS_BRANCH} -e TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE} -e TRAVIS_PULL_REQUEST_SLUG=${TRAVIS_PULL_REQUEST_SLUG} -e TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH} kalliope-ubuntu2004

before_install:
  - |
    if [ "${INSTALL_TYPE}" == "setup" ]; then
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse"
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse"
      sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse"
      sudo add-apt-repository -y ppa:deadsnakes/ppa # contains libpython3.6-dev
      sudo apt-get update -q
      sudo apt-get install $(cat install/files/deb-packages_requirements.txt)
      sudo apt-get install gcc-5 python3-dev libpython3.6-dev
    fi
install:
  - |
    if [ "${INSTALL_TYPE}" == "setup" ]; then
      pip install -r install/files/python_requirements.txt;
      pip install coverage python-coveralls;
    fi
script:
  - |
    if [ "${INSTALL_TYPE}" == "setup" ]; then
      coverage run --source=kalliope -m unittest discover;
      coverage report -m;
    fi
after_success:
 - |
    if [ "${INSTALL_TYPE}" == "setup" ]; then
      coveralls
    fi
